apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    tier: backend
spec:
<<<<<<< HEAD
  replicas: 3
=======
  replicas: 8
>>>>>>> f1475428cada91da690bd9b1dea6b813942b5b80
  selector:
    matchLabels:
      app: php
      tier: backend
  template:
    metadata:
      labels:
        app: php
        tier: backend
    spec:
      volumes:
      - name: dir
        hostPath:
          path: /code
      containers:
      - name: php
        image: kiyange26773/web:v1.0
        volumeMounts:
        - name: dir
          mountPath: /code
      initContainers:
      - name: install
        image: busybox
        volumeMounts:
        - name: dir
          mountPath: /code
        command:
        - cp
        - "-r"
        - "/var/www/."
        - "/code/app"
